### ISSUE TITLE
Breakfast - Equipment

### ISSUE THREAD

**Issue by hoangcto** [IntroToCode/CodeMates3_Fall22#4]
## 💬 Discussion topic

Need to figure out what equipment are needed

## ❗ Potential issues

Cannot make food without the right tools

## 👥 People to consult

@luisfego @chaley17 

## 📃 Details

@Tojtt to figure out what equipment is needed and add to breakfast recipe 😃

**Comment by fbosselin** [comment]
Hey @Tojtt just checking, am I one of the "People to consult"? Because there a "@luisfego" who is not from the team
